project 'Home.xcodeproj'

# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'Home' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking'#网络请求
pod 'SDWebImage'#图片加载
pod 'MJRefresh'#下拉刷新加载
pod 'IQKeyboardManager'#键盘管理
pod 'Masonry'#第三方布局
pod 'MBProgressHUD'
pod 'MWPhotoBrowser'#环信通信组件图片浏览
pod 'SDAutoLayout'#布局
pod 'JSONModel'#字典转模型
pod 'TTGTagCollectionView'#标签显示
pod 'GVRSDK'
  # Pods for Home
end
